---
# Service Verification Helper
# Usage:
# - include_tasks: ../helpers/service_verify.yml
#   vars:
#     service_name: "xrdp"
#     expected_port: 3389 (optional)
#     retries: 5 (optional, default: 3)

- name: "Set default retries"
  set_fact:
    verify_retries: "{{ retries | default(3) }}"

- name: "Verify service {{ service_name }} is running"
  systemd:
    name: "{{ service_name }}"
    state: started
  register: service_status
  until: service_status.status.ActiveState == 'active'
  retries: "{{ verify_retries }}"
  delay: 5
  ignore_errors: true
  when: ansible_facts['virtualization_type'] | default('none') != 'docker'

- name: "Assert service state"
  assert:
    that:
      - service_status.status.ActiveState == 'active'
      - service_status.status.SubState == 'running'
    fail_msg: "Service {{ service_name }} failed to start. Status: {{ service_status.status.ActiveState }}"
  when: ansible_facts['virtualization_type'] | default('none') != 'docker'

- name: "Verify port {{ expected_port }} is listening"
  wait_for:
    port: "{{ expected_port }}"
    timeout: 5
    state: started
  when: expected_port is defined
  register: port_check
  ignore_errors: true

- name: "Assert port state"
  assert:
    that:
      - port_check is succeeded
    fail_msg: "Port {{ expected_port }} is not listening for service {{ service_name }}"
  when: expected_port is defined
