---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(\.agent|\.github)/
      - id: end-of-file-fixer
        exclude: ^(\.agent|\.github)/
      - id: check-yaml
        exclude: ^(\.agent|\.github)/
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        exclude: ^(\.agent|\.github)/

  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        files: \.(yaml|yml)$
        types: [yaml]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: ^scripts/.*\.j2$ # Exclude templates
        args: ["-e", "SC2155,SC2317,SC2248,SC2059,SC2002,SC2162,SC2310,SC2012,SC1091,SC2124,SC2010,SC2164,SC2181,SC2086,SC2034,SC2046"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
        exclude: ^(\.agent|\.github)/
