---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-security
    image: molecule_local/debian:trixie
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    stop_signal: SIGRTMIN+3
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    groups:
      - security_group
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections

verifier:
  name: ansible
