---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-security
    image: molecule_local/debian:trixie
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    groups:
      - security_group
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: ansible.builtin.default
      callback_result_format: yaml
      callbacks_enabled: profile_tasks, timer
    ssh_connection:
      pipelining: false
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
verifier:
  name: ansible
