---
dependency:
  name: galaxy
driver:
  name: lxd
platforms:
  - name: security-instance
    image: images:debian/12
    type: container
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections

verifier:
  name: ansible
