---
- name: Verify
  hosts: all
  tasks:
    - name: "Check SSH configuration"
      ansible.builtin.command:
        cmd: grep "^PermitRootLogin no" /etc/ssh/sshd_config
      register: ssh_root_login
      changed_when: false

    - name: "Assert Root Login Disabled"
      ansible.builtin.assert:
        that:
          - ssh_root_login.rc == 0
        fail_msg: "PermitRootLogin is not set to 'no'"

    - name: "Check UFW status (Debian/Ubuntu)"
      ansible.builtin.command:
        cmd: ufw status
      register: ufw_status
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: "Assert UFW is active"
      ansible.builtin.assert:
        that:
          - "'Status: active' in ufw_status.stdout"
      when: ansible_facts['os_family'] == "Debian" and ufw_status is not skipped

    - name: "Check Fail2Ban service"
      ansible.builtin.include_tasks: ../helpers/service_verify.yml
      vars:
        service_name: "fail2ban"
