---
- name: Verify
  hosts: all
  tasks:
    - name: "Check SSH configuration"
      command: grep "^PermitRootLogin no" /etc/ssh/sshd_config
      register: ssh_root_login
      changed_when: false
      ignore_errors: true

    - name: "Assert Root Login Disabled"
      assert:
        that:
          - ssh_root_login.rc == 0
        fail_msg: "PermitRootLogin is not set to 'no'"

    - name: "Check UFW status (Debian/Ubuntu)"
      command: ufw status
      register: ufw_status
      changed_when: false
      when: ansible_os_family == "Debian"
      ignore_errors: true

    - name: "Assert UFW is active"
      assert:
        that:
          - "'Status: active' in ufw_status.stdout"
      when: ansible_os_family == "Debian" and ufw_status is not skipped

    - name: "Check Fail2Ban service"
      include_tasks: ../helpers/service_verify.yml
      vars:
        service_name: "fail2ban"
      ignore_errors: true # Might not be installed in all security profiles
