---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    managed: true
platforms:
  - name: chaos-instance
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence # Disabled for chaos testing
    - side_effect
    - verify
    - cleanup
    - destroy
