class CallbackBase:
    CALLBACK_VERSION: float
    CALLBACK_TYPE: str
    CALLBACK_NAME: str
    CALLBACK_NEEDS_WHITELIST: bool
    def __init__(self) -> None: ...
    def v2_playbook_on_start(self, playbook: object) -> None: ...
    def v2_playbook_on_task_start(self, task: object, is_conditional: bool) -> None: ...
    def v2_runner_on_ok(self, result: object) -> None: ...
    def v2_runner_on_failed(self, result: object, ignore_errors: bool = ...) -> None: ...
    def v2_runner_on_skipped(self, result: object) -> None: ...
    def v2_runner_on_unreachable(self, result: object) -> None: ...
    def v2_playbook_on_stats(self, stats: object) -> None: ...
