---
# Molecule converge playbook
# Tests the common role

- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - ../../tests/strict_vars.yml

  roles:
    # Phase 1: Bootstrap
    - role: common
    - role: security

    # Phase 2: Base System
    - role: fonts

    # Phase 3: Desktop Environment
    # - role: desktop # Disabled to prevent timeout in CI
    # - role: xrdp # Disabled for CI
    - role: kde-optimization
    # - role: kde-apps # Disabled for CI
    - role: whitesur-theme

    # Phase 4: User Configuration
    - role: terminal
    - role: shell-styling
    - role: zsh-enhancements

    # Phase 5: Development Tools
    - role: development
    - role: docker
    - role: editors

    # Phase 6: CLI Tool Roles
    - role: tui-tools
    - role: network-tools
    - role: system-performance
    - role: text-processing
    - role: file-management
    - role: dev-debugging
    - role: code-quality
    - role: productivity
    - role: log-visualization
    - role: ai-devtools
    - role: cloud-native
