---
# Molecule converge: Bootstrap & Security
# Tests the foundational roles that every deployment must pass

- name: Converge - Bootstrap and Security
  hosts: all
  become: true
  gather_facts: true

  vars:
    vps_username: "testuser"
    # Use a secure hash for testing (this is 'password')
    vps_user_password_hash: "$6$.Ojg0ni41Tt7qud2$jzkcbgP2xuzr8M4cdHEXKOO9laed1qqqxvOigLRG8rSxF8j1mtZ5Peukhrx.uQfW.YBvPHoSj.IFczSPYwjPO/"
    vps_install_desktop: true
    vps_install_xrdp: true
  pre_tasks:
    - name: Debug Ansible Configuration
      ansible.builtin.debug:
        msg:
          - "Config file magic var: {{ query('config', 'CONFIG_FILE') }}"
          - "Callback plugins config: {{ query('config', 'DEFAULT_CALLBACK_PLUGIN_PATH') }}"
          - "Callbacks enabled config: {{ query('config', 'CALLBACKS_ENABLED') }}"
          - "Environment ANSIBLE_CONFIG: {{ ansible_facts.env.ANSIBLE_CONFIG | default('NOT SET') }}"
          - "Environment ANSIBLE_CALLBACK_PLUGINS: {{ ansible_facts.env.ANSIBLE_CALLBACK_PLUGINS | default('NOT SET') }}"

  roles:
    - role: common
    - role: security
    - role: desktop
    - role: xrdp
