FROM {{ item.image }}
ENV container docker
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       systemd \
       systemd-sysv \
       python3 \
       sudo \
       bash \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
CMD ["/lib/systemd/systemd"]
