---
# Molecule configuration for VPS RDP Workstation roles
# Run: molecule test
# Docs: https://molecule.readthedocs.io/

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: debian-trixie
    image: debian:trixie
    pre_build_image: true
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    # Use standard init which is available in base image, or install systemd if needed
    # debian:trixie base image might not have systemd installed by default
    # Use raw image. Python and sudo will be installed via prepare.yml using raw module.
    # We also create a dummy systemd placeholder if missing to satisfy checks
    command: >-
      /bin/sh -c "if [ -x /lib/systemd/systemd ]; then exec /lib/systemd/systemd;
      else echo 'Systemd not found, sleeping' && while true; do sleep 1000; done; fi"
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  env:
    # Fix duplicate collection warnings by strictly defining the path
    # Using only molecule managed collections path to avoid conflicts
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_EPHEMERAL_DIRECTORY}/collections
    # Suppress deprecation warnings
    ANSIBLE_DEPRECATION_WARNINGS: "False"
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      stdout_callback: yaml
      roles_path: /home/apexdev/Desktop/Testing/vps-rdp-workstation/roles
      remote_tmp: /tmp/.ansible/tmp
      allow_world_readable_tmpfiles: true
      pipelining: true
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      debian-trixie:
        ansible_user: root
        ansible_become_password: "gg123123@"
        vps_fail2ban_enabled: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
