---
# Molecule Scenario: default (common + security roles)
# Tests core system bootstrap and security hardening in a Debian container
# Run: molecule test

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/requirements.yml
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: debian-trixie
    image: debian:trixie
    pre_build_image: true
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: "${MOLECULE_PROJECT_DIRECTORY}/ansible.cfg"
    ANSIBLE_DEPRECATION_WARNINGS: "True"
    ANSIBLE_WARNINGS_ARE_ERRORS: "True"
    ANSIBLE_SYSTEM_WARNINGS: "True"
    ANSIBLE_CALLBACK_PLUGINS: "${MOLECULE_PROJECT_DIRECTORY}/plugins/callback"
    ANSIBLE_CALLBACKS_ENABLED: "strict_deprecations"
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections
      remote_tmp: /tmp/.ansible/tmp
      allow_world_readable_tmpfiles: true
      pipelining: true
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      debian-trixie:
        ansible_user: root
        vps_fail2ban_start_service: false
      localhost:
        ansible_connection: local
        ansible_become: false

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
