---
# Molecule configuration for VPS RDP Workstation roles
# Run: molecule test
# Docs: https://molecule.readthedocs.io/

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: debian-trixie
    image: debian:trixie
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    # Use standard init which is available in base image, or install systemd if needed
    # debian:trixie base image might not have systemd installed by default
    # Use raw image and install python manually in prepare step, or pre-install via shell
    # NOTE: We force python3 install via command because raw image lacks it, causing ansible to fail gathering facts
    command: /bin/bash -c "apt-get update && apt-get install -y python3 python3-pip && if [ -x /lib/systemd/systemd ]; then /lib/systemd/systemd; else echo 'Systemd not found, sleeping' && while true; do sleep 1000; done; fi"
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      stdout_callback: yaml
      roles_path: /home/apexdev/Desktop/Testing/vps-rdp-workstation/roles
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      debian-trixie:
        ansible_user: root

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
