---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap Python
      raw: apt-get update && apt-get install -y python3 python3-pip sudo
      changed_when: true
      ignore_errors: true
