---
# Molecule verify playbook
# Validates that the role was applied correctly

- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure validation directory structure exists
      ansible.builtin.file:
        path: /root/repo/tests
        state: directory
        mode: '0755'

    - name: Copy project components (lightweight)
      ansible.builtin.copy:
        src: "../../{{ item }}"
        dest: "/root/repo/"
        mode: preserve
      loop:
        - setup.sh
        - README.md
        - tests
        - docs
        - playbooks
        - plugins
        - templates

    - name: Archive roles locally
      community.general.archive:
        path: ../../roles
        dest: /tmp/roles.tar.gz
        format: gz
        mode: '0644'
      delegate_to: localhost

    - name: Copy roles archive
      ansible.builtin.copy:
        src: /tmp/roles.tar.gz
        dest: /tmp/roles.tar.gz
        mode: '0644'

    - name: Unarchive roles
      ansible.builtin.unarchive:
        src: /tmp/roles.tar.gz
        dest: /root/repo/
        remote_src: true

    - name: Run validation suite
      ansible.builtin.command: bash tests/validate.sh
      args:
        chdir: /root/repo
      register: validation_output
      changed_when: false
      ignore_errors: true

    - name: Display validation output
      ansible.builtin.debug:
        msg: "{{ validation_output.stdout_lines }}"

    - name: Fail if validation failed
      ansible.builtin.fail:
        msg: "Validation suite failed! See output above."
      when: validation_output.rc != 0
