---
# Molecule verify: Bootstrap & Security assertions
# Validates that common + security roles applied correctly

- name: Verify - Bootstrap and Security
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # =========================================================================
    #  Common Role Assertions
    # =========================================================================

    - name: Verify user exists
      ansible.builtin.getent:
        database: passwd
        key: testuser
      register: user_check

    - name: Assert user was created
      ansible.builtin.assert:
        that: user_check is not failed
        fail_msg: "User testuser was not created by common role"

    - name: Verify essential packages installed
      ansible.builtin.command: "dpkg -l {{ item }}"
      loop:
        - git
        - curl
        - wget
        - vim
        - zsh
        - sudo
      register: pkg_check
      changed_when: false
      failed_when: pkg_check.rc != 0

    - name: Verify hostname was set
      ansible.builtin.slurp:
        src: /etc/hostname
      register: hostname_check

    - name: Assert hostname is correct
      ansible.builtin.assert:
        that: "'molecule-test' in (hostname_check.content | b64decode)"
        fail_msg: "Hostname not set correctly in /etc/hostname"

    - name: Verify state tracking directory exists
      ansible.builtin.stat:
        path: /var/lib/vps-setup
      register: state_dir

    - name: Assert state directory created
      ansible.builtin.assert:
        that: state_dir.stat.exists and state_dir.stat.isdir
        fail_msg: "State tracking directory not created"

    - name: Verify sudoers file for user
      ansible.builtin.stat:
        path: /etc/sudoers.d/testuser
      register: sudoers_check

    - name: Assert sudoers configured
      ansible.builtin.assert:
        that: sudoers_check.stat.exists
        fail_msg: "Sudoers file not created for testuser"

    # =========================================================================
    #  Security Role Assertions
    # =========================================================================

    - name: Verify UFW is installed
      ansible.builtin.command: dpkg -l ufw
      register: ufw_check
      changed_when: false
      failed_when: ufw_check.rc != 0

    - name: Verify SSH server installed
      ansible.builtin.command: dpkg -l openssh-server
      register: ssh_check
      changed_when: false
      failed_when: ssh_check.rc != 0

    - name: Verify SSH config exists
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config
      register: sshd_config

    - name: Assert SSH config present
      ansible.builtin.assert:
        that: sshd_config.stat.exists
        fail_msg: "SSH config not found"

    - name: Verify SSH backup was created
      ansible.builtin.stat:
        path: /var/backups/vps-setup/sshd_config.backup
      register: ssh_backup

    - name: Assert SSH backup exists
      ansible.builtin.assert:
        that: ssh_backup.stat.exists
        fail_msg: "SSH config backup not created by security role"
