---
# Molecule verify: Bootstrap & Security assertions
# Validates that common + security roles applied correctly

- name: Verify - Bootstrap and Security
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # =========================================================================
    #  Common Role Assertions
    # =========================================================================

    - name: Verify user exists
      ansible.builtin.getent:
        database: passwd
        key: testuser
      register: user_check

    - name: Assert user was created
      ansible.builtin.assert:
        that: user_check is not failed
        fail_msg: "User testuser was not created by common role"

    - name: Verify essential packages installed
      ansible.builtin.command: "dpkg -l {{ item }}"
      loop:
        - git
        - curl
        - wget
        - vim
        - zsh
        - sudo
      register: pkg_check
      changed_when: false
      failed_when: pkg_check.rc != 0

    - name: Verify hostname was set
      ansible.builtin.slurp:
        src: /etc/hostname
      register: hostname_check

    - name: Assert hostname is correct
      ansible.builtin.assert:
        that: "'dev-workstation' in (hostname_check.content | b64decode)"
        fail_msg: "Hostname not set correctly in /etc/hostname"

    - name: Verify state tracking directory exists
      ansible.builtin.stat:
        path: /var/lib/vps-setup
      register: state_dir

    - name: Assert state directory created
      ansible.builtin.assert:
        that: state_dir.stat.exists and state_dir.stat.isdir
        fail_msg: "State tracking directory not created"

    - name: Verify sudoers file for user
      ansible.builtin.stat:
        path: /etc/sudoers.d/testuser
      register: sudoers_check

    - name: Assert sudoers configured
      ansible.builtin.assert:
        that: sudoers_check.stat.exists
        fail_msg: "Sudoers file not created for testuser"

    # =========================================================================
    #  Security Role Assertions
    # =========================================================================

    - name: Verify UFW is installed
      ansible.builtin.command: dpkg -l ufw
      register: ufw_check
      changed_when: false
      failed_when: ufw_check.rc != 0

    - name: Verify SSH server installed
      ansible.builtin.command: dpkg -l openssh-server
      register: ssh_check
      changed_when: false
      failed_when: ssh_check.rc != 0

    - name: Verify SSH config exists
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config
      register: sshd_config

    - name: Assert SSH config present
      ansible.builtin.assert:
        that: sshd_config.stat.exists
        fail_msg: "SSH config not found"

    - name: Verify SSH backup was created
      ansible.builtin.stat:
        path: /var/backups/vps-setup/sshd_config.backup
      register: ssh_backup

    - name: Assert SSH backup exists
      ansible.builtin.assert:
        that: ssh_backup.stat.exists
        fail_msg: "SSH config backup not created by security role"

    # =========================================================================
    #  Desktop & XRDP Role Assertions
    # =========================================================================

    - name: Verify XRDP configuration exists
      ansible.builtin.stat:
        path: /etc/xrdp/xrdp.ini
      register: xrdp_conf

    - name: Assert XRDP configuration exists
      ansible.builtin.assert:
        that: xrdp_conf.stat.exists
        fail_msg: "XRDP configuration file /etc/xrdp/xrdp.ini is missing"
    - name: Verify xorgxrdp is installed
      ansible.builtin.command: dpkg -l xorgxrdp
      register: xorgxrdp_check
      changed_when: false
      failed_when: xorgxrdp_check.rc != 0

    - name: Verify KDE Plasma session executable exists
      ansible.builtin.stat:
        path: /usr/bin/startplasma-x11
      register: kde_session

    - name: Assert KDE Plasma installed
      ansible.builtin.assert:
        that: kde_session.stat.exists
        fail_msg: "KDE Plasma session executable not found"

    # =========================================================================
    #  Shell & User Role Assertions
    # =========================================================================

    - name: Verify testuser shell is Zsh
      ansible.builtin.user:
        name: testuser
        state: present
      register: user_info

    - name: Assert user shell is zsh
      ansible.builtin.assert:
        that: user_info.shell in ['/usr/bin/zsh', '/bin/zsh']
        fail_msg: "User shell is not set to zsh (found {{ user_info.shell }})"

    # =========================================================================
    #  Service Health Checks
    # =========================================================================

    - name: Verify XRDP service status
      ansible.builtin.systemd:
        name: xrdp
      register: xrdp_service_check
      failed_when: false

    - name: Report XRDP service status
      ansible.builtin.debug:
        msg: "XRDP service status: {{ xrdp_service_check.status.ActiveState | default('unknown') }}"

    - name: Verify XRDP configuration is valid
      ansible.builtin.stat:
        path: /etc/xrdp/xrdp.ini
      register: xrdp_config_check

    - name: Assert XRDP configuration exists
      ansible.builtin.assert:
        that: xrdp_config_check.stat.exists
        fail_msg: "XRDP configuration file not found"

    - name: Verify fail2ban configuration exists
      ansible.builtin.stat:
        path: /etc/fail2ban/jail.local
      register: fail2ban_config_check

    - name: Assert fail2ban is configured
      ansible.builtin.assert:
        that: fail2ban_config_check.stat.exists
        fail_msg: "Fail2ban jail.local configuration not found"
