---
- name: Converge
  hosts: all
  vars_files:
    - ../fixtures/test_data.yml
  vars:
    vps_username: root
  tasks:
    - name: "Include role tui-tools"
      include_role:
        name: tui-tools
