---
# Molecule verify: Shell assertions

- name: Verify - Shell Configuration
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # =========================================================================
    #  Terminal / Zsh Assertions
    # =========================================================================

    - name: Verify Zsh installed
      ansible.builtin.command: zsh --version
      register: zsh_check
      changed_when: false
      failed_when: zsh_check.rc != 0

    - name: Verify Oh My Zsh installed
      ansible.builtin.stat:
        path: /home/testuser/.oh-my-zsh
      register: omz_check

    - name: Assert OMZ exists
      ansible.builtin.assert:
        that: omz_check.stat.exists and omz_check.stat.isdir
        fail_msg: "Oh My Zsh directory not found"

    - name: Verify .zshrc exists
      ansible.builtin.stat:
        path: /home/testuser/.zshrc
      register: zshrc_check

    - name: Assert .zshrc created
      ansible.builtin.assert:
        that: zshrc_check.stat.exists
        fail_msg: ".zshrc does not exist"

    - name: Check Zsh theme configuration
      ansible.builtin.command: grep -E 'ZSH_THEME="agnoster"|source.*agnoster' /home/testuser/.zshrc
      register: theme_check
      changed_when: false
      failed_when: theme_check.rc != 0

    # =========================================================================
    #  Tmux Assertions
    # =========================================================================

    - name: Verify Tmux installed
      ansible.builtin.command: tmux -V
      register: tmux_check
      changed_when: false
      failed_when: tmux_check.rc != 0

    - name: Verify .tmux.conf exists
      ansible.builtin.stat:
        path: /home/testuser/.tmux.conf
      register: tmuxconf_check

    - name: Assert .tmux.conf exists
      ansible.builtin.assert:
        that: tmuxconf_check.stat.exists
        fail_msg: ".tmux.conf not found"

    # =========================================================================
    #  Starship/Styling Assertions
    # =========================================================================

    - name: Verify Starship config exists (if shell-styling ran)
      ansible.builtin.stat:
        path: /home/testuser/.config/starship.toml
      register: starship_check

    - name: Assert Starship config (optional based on role)
      ansible.builtin.assert:
        that: starship_check.stat.exists
        fail_msg: "Starship config not found"

    # =========================================================================
    #  Shell Enhancement Health Checks
    # =========================================================================

    - name: Verify zsh-autosuggestions plugin installed
      ansible.builtin.stat:
        path: /home/testuser/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      register: autosuggestions_check

    - name: Assert zsh-autosuggestions exists
      ansible.builtin.assert:
        that: autosuggestions_check.stat.exists and autosuggestions_check.stat.isdir
        fail_msg: "zsh-autosuggestions plugin not installed"

    - name: Verify zsh-syntax-highlighting plugin installed
      ansible.builtin.stat:
        path: /home/testuser/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      register: syntax_highlighting_check

    - name: Assert zsh-syntax-highlighting exists
      ansible.builtin.assert:
        that: syntax_highlighting_check.stat.exists and syntax_highlighting_check.stat.isdir
        fail_msg: "zsh-syntax-highlighting plugin not installed"

    - name: Verify fzf is installed
      ansible.builtin.command: which fzf
      register: fzf_check
      changed_when: false
      failed_when: false

    - name: Report fzf status
      ansible.builtin.debug:
        msg: "fzf: {{ 'installed at ' + fzf_check.stdout if fzf_check.rc == 0 else 'not installed (may require manual setup)' }}"

    - name: Verify zoxide is installed
      ansible.builtin.command: which zoxide
      register: zoxide_check
      changed_when: false
      failed_when: false

    - name: Report zoxide status
      ansible.builtin.debug:
        msg: "zoxide: {{ 'installed at ' + zoxide_check.stdout if zoxide_check.rc == 0 else 'not installed (external installer may not run in container)' }}"
