---
# Molecule Scenario: rollback
# Tests that the rollback playbook correctly reverses deployment
# Run: molecule test -s rollback

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/requirements.yml
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: debian-rollback
    image: debian:trixie
    dockerfile: ../default/Dockerfile.j2
    pre_build_image: false
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections

verifier:
  name: ansible

scenario:
  name: rollback
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
