---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap Python
      ansible.builtin.raw: |
        test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3-minimal python3-apt sudo)
      register: bootstrap_python
      changed_when: "'Reading package lists' in bootstrap_python.stdout"

    - name: Create remote_tmp directory
      ansible.builtin.file:
        path: "/tmp/.ansible/tmp"
        state: directory
        mode: '1777'

    - name: Create SSH privilege separation directory
      ansible.builtin.file:
        path: "/run/sshd"
        state: directory
        mode: '0755'
